# Generated by Django 5.0.2 on 2024-06-04 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offer', '0002_alter_offer_seller'),
        ('shopping_car', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarContainsOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_product', to='offer.offer')),
                ('shopping_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_car', to='shopping_car.shoppingcar')),
            ],
        ),
    ]
