# Generated by Django 5.0.2 on 2024-06-12 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='gamekey',
            field=models.CharField(default='Product', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='title',
            field=models.CharField(default='Default Title', max_length=100),
            preserve_default=False,
        ),
    ]
