# Generated by Django 5.0.2 on 2024-06-25 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_alter_offer_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='description',
            field=models.TextField(default='No description yet'),
        ),
        migrations.AddField(
            model_name='offer',
            name='gamekey',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
